version: "3"
name: money-split-container
services:
  main-db:
    image: "mysql"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=${MYSQL_ROOT_PASSWORD}
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 55
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - db-data:/main
    networks:
      main:

  frontend:
    image: "money-split-frontend"
    environment:
      - MIDDLEWARE_URL=${MIDDLEWARE_URL}
    networks:
      main:
        aliases:
          - frontend

  data-provider:
    image: "money-split-data-provider"
    environment:
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PORT=3306
      - JWT_SECRET=${JWT_SECRET}
      - TZ=${TZ}
    depends_on:
      main-db:
        condition: service_healthy
    networks:
      main:
        aliases:
          - data-provider

  admin-dashboard:
    image: "money-split-admin-dashboard"
    environment:
      - MIGRATION_MANAGER_URL=${MIGRATION_MANAGER_URL}
    networks:
      main:
        aliases:
          - admin-dashboard

  migration-manager:
    image: "money-split-migration-manager"
    environment:
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PORT=3306
      - ADMIN_MIGRATION_PASSWORD=${ADMIN_MIGRATION_PASSWORD}
      - TZ=${TZ}
      - MIDDLEWARE_URL_INTERNAL=${MIDDLEWARE_URL_INTERNAL}
    depends_on:
      main-db:
        condition: service_healthy
    networks:
      main:
        aliases:
          - migration-manager

  proxy:
    image: "money-split-proxy"
    ports:
      - 8310:80
      - 8311:443
    links:
      - frontend:frontend
    depends_on:
      - frontend
      - migration-manager
    networks:
      main:
        aliases:
           - nginx

volumes:
  db-data:

networks:
  main: