export enum ERROR_CODE {
    RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND',
    RESOURCE_ALREADY_EXISTS = 'RESOURCE_ALREADY_EXISTS',
    REQUESTED_ONE_FOUND_MULTIPLE = 'REQUESTED_ONE_FOUND_MULTIPLE',
    LAST_INSERT_ID_ERROR = 'LAST_INSERT_ID_ERROR',
    UNAUTHORIZED = 'UNAUTHORIZED',
    INVALID_REQUEST = 'INVALID_REQUEST',
    OWNER_USERNAME_ALREADY_EXISTS = 'OWNER_USERNAME_ALREADY_EXISTS',
    USER_ACTION_CONFLICT = 'USER_ACTION_CONFLICT',
    PROCEDURE_ERROR = 'PROCEDURE_ERROR',
    FILE_UPLOAD_ERROR = 'FILE_UPLOAD_ERROR',
}

export interface GuiError extends Error {
  message: string;
  code?: ERROR_CODE;
  details?: Record<string, unknown>;
}