version: "3"
services:
  db:
    image: "mysql"
    environment:
      MYSQL_ROOT_PASSWORD: anze123
      MYSQL_DATABASE: main
    ports:
      - "13307:3306"

    volumes:
      - db-data:/main

volumes:
  db-data: