version: "3"
name: money-split-local-container
services:
  main-db:
    image: "mysql"
    env_file:
      - ../.env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "${MYSQL_PORT}:3306"

    volumes:
      - db-data:/main

volumes:
  db-data: