version: "3"
name: money-split-local-container
services:
  main-db:
    image: "mysql"
    environment:
      MYSQL_ROOT_PASSWORD: anze123
      MYSQL_DATABASE: main
    ports:
      - "13308:3306"

    volumes:
      - db-data:/main

volumes:
  db-data: